apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: frontend
  name: frontend-ingress
  labels:
    tier: frontend
spec:
  # defaultBackend:

  rules:
    - host: www.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-node-port-svc
                port:
                  number: 3000
