---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    tier: db
    space: db-space
spec: {}
status: {}

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    tier: backend
    space: backend-space
spec: {}
status: {}

---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    tier: client
    space: client-space
spec: {}
status: {}
