---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    tier: db
spec: {}
status: {}

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    tier: backend
spec: {}
status: {}

---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    tier: client
spec: {}
status: {}
