apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: db
  name: db-pvc
  labels:
    type: postgres-db-pvc
spec:
  storageClassName: ''
  volumeName: db-pv
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      type: host-pv
  resources:
    requests:
      storage: '500Mi'
