apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: frontend
  name: frontend-hpa
  labels:
    tier: client
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  targetCPUUtilizationPercentage: 70
