# Backend service for local testing
---
apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: backend-node-port-svc
  labels:
    task: backend-node-port-svc
spec:
  ports:
    - name: backend
      targetPort: 8000
      port: 80
      nodePort: 30080
  selector:
    tier: backend
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: backend-clusterip-svc
  labels:
    task: backend-clusterip-svc
spec:
  ports:
    - name: backend
      targetPort: 8000
      port: 80
  selector:
    tier: backend
  type: ClusterIP
