---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: db
  name: default-deny-netpol
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: db
  name: db-netpol
spec:
  podSelector:
    matchLabels:
      tier: db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              tier: backend
          podSelector:
            matchLabels:
              tier: backend
      ports:
        - protocol: TCP
          port: 5432
    # - from:
    #     - ipBlock:
    #         cidr: 192.168.0.0/0
    #   ports:
    #     - protocol: TCP
    #       port: 5432
    #     - protocol: TCP
    #       port: 30432
